buildscript {
    ext {
        version_android_gradle_plugin = '8.13.2'
        version_core = "1.18.0"
        version_constraint_layout = "2.2.1"
        version_glide = "5.0.7"
        version_kotlin = '2.3.21'
        version_ksp = '2.3.7'
        version_kotlin_coroutines = "1.10.2"
        version_lifecycle = '2.10.0'
        version_moshi = "1.15.2"
        version_navigation = "2.9.8"
        version_retrofit = "3.0.0"
        version_retrofit_coroutines_adapter = "0.9.2"
        version_recyclerview = "1.2.0-alpha05"
        version_play_services_location = "21.3.0"
        version_room = "2.8.4"
        version_timber = "5.0.1"
        version_koin = "4.2.1"
    }

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:$version_android_gradle_plugin"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$version_kotlin"
        classpath "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:$version_ksp"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$version_navigation"
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}